<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture.Xunit3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="pythonnet" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.core" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Python\pyproject.toml" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Python\uv.lock" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Iceberg.Net.Tests\Iceberg.Net.Tests.csproj" />
    </ItemGroup>

</Project>
