<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Apache.Arrow" Version="23.0.0" />
    <PackageVersion Include="AutoFixture.Xunit3" Version="4.19.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.101.6" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="DotNext.Metaprogramming" Version="6.5.0" />
    <PackageVersion Include="DuckDB.NET.Data.Full" Version="1.5.2" />
    <PackageVersion Include="EngineeredWood.Core" Version="0.1.0" />
    <PackageVersion Include="EngineeredWood.Aws" Version="0.1.0" />
    <PackageVersion Include="EngineeredWood.Azure" Version="0.1.0" />
    <PackageVersion Include="EngineeredWood.Expressions" Version="0.1.0" />
    <PackageVersion Include="EngineeredWood.Gcs" Version="0.1.0" />
    <PackageVersion Include="EngineeredWood.Iceberg" Version="0.1.0" />
    <PackageVersion Include="FastExpressionCompiler" Version="5.4.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Kiota.Bundle" Version="2.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageVersion Include="Nuqleon.Linq.CompilerServices" Version="1.0.0-beta.24" />
    <PackageVersion Include="Nuqleon.Linq.CompilerServices.Optimizers" Version="1.0.0-beta.24" />
    <PackageVersion Include="Nuqleon.Linq.Expressions.Optimizers" Version="1.0.0-beta.24" />
    <PackageVersion Include="ParquetSharp" Version="24.0.0" />
    <PackageVersion Include="System.IO.Hashing" Version="9.0.18" />
    <PackageVersion Include="Testcontainers" Version="4.11.0" />
    <PackageVersion Include="Testcontainers.XunitV3" Version="4.11.0" />
    <PackageVersion Include="Varena" Version="1.2.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.core" Version="3.2.2" />
    <PackageVersion Include="ZLinq" Version="1.5.6" />
  </ItemGroup>
</Project>
