<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture.Xunit3" />
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="DuckDB.NET.Data.Full" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="Testcontainers.XunitV3" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.core" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Iceberg.Net.DuckUtils\Iceberg.Net.DuckUtils.csproj" />
        <ProjectReference Include="..\Iceberg.Net\Iceberg.Net.csproj" />
        <ProjectReference Include="..\Iceberg.Net.Parquet\Iceberg.Net.Parquet.csproj" />
        <ProjectReference Include="..\Iceberg.Net.Rest\Iceberg.Net.Rest.csproj" />
        <ProjectReference Include="..\Iceberg.Net.S3\Iceberg.Net.S3.csproj" />
        <ProjectReference Include="..\Apache.Arrow.Serialization.Generator\Apache.Arrow.Serialization.Generator.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
