<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsAotCompatible>true</IsAotCompatible>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EngineeredWood.Core"/>
        <PackageReference Include="EngineeredWood.Expressions"/>
        <PackageReference Include="EngineeredWood.Expressions.Arrow"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <ProjectReference Include="..\Apache.Arrow.Serialization\Apache.Arrow.Serialization.csproj"/>
        <ProjectReference Include="..\EngineeredWood.Avro\EngineeredWood.Avro.csproj"/>
    </ItemGroup>

</Project>
