using EngineeredWood.Avro;

namespace Iceberg.Net.Metadata;

internal static class ManifestAvroSchemas
{
    internal static readonly AvroSchema ManifestEntry = new(ManifestEntryV2);
    internal static readonly AvroSchema ManifestList = new(ManifestListV2);

    private const string ManifestEntryV2 =
        """{"type":"record","fields":[{"name":"status","field-id":0,"type":"int"},{"name":"snapshot_id","field-id":1,"type":["null","long"],"default":null},{"name":"sequence_number","field-id":3,"type":["null","long"],"default":null},{"name":"file_sequence_number","field-id":4,"type":["null","long"],"default":null},{"name":"data_file","field-id":2,"type":{"type":"record","fields":[{"name":"content","field-id":134,"type":"int"},{"name":"file_path","field-id":100,"type":"string"},{"name":"file_format","field-id":101,"type":"string"},{"name":"partition","field-id":102,"type":{"type":"record","fields":[],"name":"r102"}},{"name":"record_count","field-id":103,"type":"long"},{"name":"file_size_in_bytes","field-id":104,"type":"long"},{"name":"column_sizes","field-id":108,"type":["null",{"type":"array","items":{"type":"record","name":"k117_v118","fields":[{"name":"key","type":"int","field-id":117},{"name":"value","type":"long","field-id":118}]},"logicalType":"map"}],"default":null},{"name":"value_counts","field-id":109,"type":["null",{"type":"array","items":{"type":"record","name":"k119_v120","fields":[{"name":"key","type":"int","field-id":119},{"name":"value","type":"long","field-id":120}]},"logicalType":"map"}],"default":null},{"name":"null_value_counts","field-id":110,"type":["null",{"type":"array","items":{"type":"record","name":"k121_v122","fields":[{"name":"key","type":"int","field-id":121},{"name":"value","type":"long","field-id":122}]},"logicalType":"map"}],"default":null},{"name":"nan_value_counts","field-id":137,"type":["null",{"type":"array","items":{"type":"record","name":"k138_v139","fields":[{"name":"key","type":"int","field-id":138},{"name":"value","type":"long","field-id":139}]},"logicalType":"map"}],"default":null},{"name":"lower_bounds","field-id":125,"type":["null",{"type":"array","items":{"type":"record","name":"k126_v127","fields":[{"name":"key","type":"int","field-id":126},{"name":"value","type":"bytes","field-id":127}]},"logicalType":"map"}],"default":null},{"name":"upper_bounds","field-id":128,"type":["null",{"type":"array","items":{"type":"record","name":"k129_v130","fields":[{"name":"key","type":"int","field-id":129},{"name":"value","type":"bytes","field-id":130}]},"logicalType":"map"}],"default":null},{"name":"key_metadata","field-id":131,"type":["null","bytes"],"default":null},{"name":"split_offsets","field-id":132,"type":["null",{"type":"array","element-id":133,"items":"long"}],"default":null},{"name":"equality_ids","field-id":135,"type":["null",{"type":"array","element-id":136,"items":"int"}],"default":null},{"name":"sort_order_id","field-id":140,"type":["null","int"],"default":null},{"name":"referenced_data_file","field-id":143,"type":["null","string"],"default":null}],"name":"r2"}}],"name":"manifest_entry"}""";

    private const string ManifestListV2 =
        """{"type":"record","fields":[{"name":"manifest_path","field-id":500,"type":"string","doc":"Location URI with FS scheme"},{"name":"manifest_length","field-id":501,"type":"long"},{"name":"partition_spec_id","field-id":502,"type":"int"},{"name":"content","field-id":517,"type":"int"},{"name":"sequence_number","field-id":515,"type":"long"},{"name":"min_sequence_number","field-id":516,"type":"long"},{"name":"added_snapshot_id","field-id":503,"type":"long"},{"name":"added_files_count","field-id":504,"type":"int"},{"name":"existing_files_count","field-id":505,"type":"int"},{"name":"deleted_files_count","field-id":506,"type":"int"},{"name":"added_rows_count","field-id":512,"type":"long"},{"name":"existing_rows_count","field-id":513,"type":"long"},{"name":"deleted_rows_count","field-id":514,"type":"long"},{"name":"partitions","field-id":507,"type":["null",{"type":"array","element-id":508,"items":{"type":"record","fields":[{"name":"contains_null","field-id":509,"type":"boolean"},{"name":"contains_nan","field-id":518,"type":["null","boolean"],"default":null},{"name":"lower_bound","field-id":510,"type":["null","bytes"],"default":null},{"name":"upper_bound","field-id":511,"type":["null","bytes"],"default":null}],"name":"r508"}}],"default":null},{"name":"key_metadata","field-id":519,"type":["null","bytes"],"default":null}],"name":"manifest_file"}""";
}
